services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    env_file:
      - path: ./.env
        required: true
    environment:
      - FRONTEND_DEV_URL=http://localhost:3000
      - FRONTEND_PRODUCT_URL=http://localhost:3000
      - NODE_ENV=production
    command: npm run dev

networks:
  Format-Sheet-backend:
    external: true
