services:
  api:
    image: aerizel/format-excel-backend
    ports:
      - 4000:4000
    restart: always
    env_file:
      - path: ./.env
        required: true
    command: ["node", "dist/index.js"]

networks:
  Format-Sheet-backend:
    external: true
