import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FloatingNavAll } from "@/components/ui/FloatingNavAll";
import { FloatingDockDemo } from "@/components/ui/FloatingDock";
import { PrimeReactProvider } from "primereact/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PrimeReactProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex flex-row p-5 justify-center items-center">
            <div className="bg-black dark:bg-white rounded-full w-[4.5rem] h-[4.5rem]"></div>
            <FloatingDockDemo />
          </div>
          {children}
        </body>
      </html>
    </PrimeReactProvider>
  );
}
